<?php

namespace ContainerO47bD08;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileEditFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProfileEditFormType' shared autowired service.
     *
     * @return \App\Form\ProfileEditFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProfileEditFormType.php';

        return $container->privates['App\\Form\\ProfileEditFormType'] = new \App\Form\ProfileEditFormType();
    }
}
