<?php

<<<<<<<< HEAD:var/cache/dev/ContainerEpHZInO/get_AssetMapper_Command_Debug_LazyService.php
namespace ContainerEpHZInO;
========
namespace ContainerOkx0b5j;
>>>>>>>> 839e19e9 (separation style):var/cache/dev/ContainerOkx0b5j/get_AssetMapper_Command_Debug_LazyService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_AssetMapper_Command_Debug_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.asset_mapper.command.debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.asset_mapper.command.debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('debug:asset-map', [], 'Output all mapped assets', false, #[\Closure(name: 'asset_mapper.command.debug', class: 'Symfony\\Component\\AssetMapper\\Command\\DebugAssetMapperCommand')] fn (): \Symfony\Component\AssetMapper\Command\DebugAssetMapperCommand => ($container->privates['asset_mapper.command.debug'] ?? $container->load('getAssetMapper_Command_DebugService')));
    }
}
