<?php

<<<<<<<< HEAD:var/cache/dev/ContainerEpHZInO/getArticleControllereditService.php
namespace ContainerEpHZInO;
========
namespace ContainerOkx0b5j;
>>>>>>>> 839e19e9 (separation style):var/cache/dev/ContainerOkx0b5j/getArticleControllereditService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d6UE9.H.App\Controller\ArticleController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.d6UE9.H'] ?? $container->load('get_ServiceLocator_D6UE9_HService'));

        if (isset($container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::edit()'])) {
            return $container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::edit()'];
        }

        return $container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::edit()'] = $a->withContext('App\\Controller\\ArticleController::edit()', $container);
    }
}
