<?php

<<<<<<<< HEAD:var/cache/dev/ContainerEpHZInO/getRegistrationControllerverifyUserEmailService.php
namespace ContainerEpHZInO;
========
namespace ContainerOkx0b5j;
>>>>>>>> 839e19e9 (separation style):var/cache/dev/ContainerOkx0b5j/getRegistrationControllerverifyUserEmailService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerverifyUserEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KHhLDTq.App\Controller\RegistrationController::verifyUserEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'translator' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::verifyUserEmail()', $container);
    }
}
