<?php

<<<<<<<< HEAD:var/cache/dev/ContainerEpHZInO/getSearchTypeService.php
namespace ContainerEpHZInO;
========
namespace ContainerOkx0b5j;
>>>>>>>> 839e19e9 (separation style):var/cache/dev/ContainerOkx0b5j/getSearchTypeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SearchType' shared autowired service.
     *
     * @return \App\Form\SearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SearchType.php';

        return $container->privates['App\\Form\\SearchType'] = new \App\Form\SearchType();
    }
}
