services:
  php:
    image: php:8.2-apache
    container_name: symfony_php
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor

  node:
    image: node:18
    container_name: vite_node
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"