version: '3.8'

services:
  mercure:
    image: dunglas/mercure:v0.15
    container_name: mercure-test
    ports:
      - "3000:80"
    environment:
      JWT_KEY: "8137a014e861c92a02da672c39b7ff608d8caebd7a7b965ce20fbb46bd39f579"
      CORS_ALLOWED_ORIGINS: "http://localhost:8000"
      PUBLISH_ALLOWED_ORIGINS: "http://localhost:8000"
      DEBUG: "1"
      CADDY_DISABLE_HTTP_REDIRECT: "1"
      CADDY_DISABLE_HTTPS: "1"
      CADDY_HTTP_PORT: "80"
      SERVER_NAME: "localhost"
