version: '3.8'

services:
  ### Backend Symfony
  backend:
    build:
      context: ./backend
    container_name: blog_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://app:!ChangeMe!@database:5432/app"
    networks:
      - blognet

  ### React Frontend (Vite)
  frontend:
    build:
      context: ./frontend
    container_name: blog_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - blognet

  ### PostgreSQL
  database:
    image: postgres:16-alpine
    container_name: blog_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blognet

  ### Mercure
  mercure:
    image: dunglas/mercure
    container_name: blog_mercure
    ports:
      - "3000:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'b96dd4a37e49a3970e77bc59299b50dade08e7d883535eff7781a2c61a771fd8'
      MERCURE_SUBSCRIBER_JWT_KEY: 'b96dd4a37e49a3970e77bc59299b50dade08e7d883535eff7781a2c61a771fd8'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000 http://localhost:5173
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - blognet

volumes:
  db_data:
  mercure_data:
  mercure_config:

networks:
  blognet:
    driver: bridge
