<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/get_Maker_AutoCommand_MakeSecurityCustom_LazyService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/get_Maker_AutoCommand_MakeSecurityCustom_LazyService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_Maker_AutoCommand_MakeSecurityCustom_LazyService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/get_Maker_AutoCommand_MakeSecurityCustom_LazyService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Maker_AutoCommand_MakeSecurityCustom_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.maker.auto_command.make_security_custom.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.maker.auto_command.make_security_custom.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:security:custom', [], 'Create a custom security authenticator.', false, #[\Closure(name: 'maker.auto_command.make_security_custom', class: 'Symfony\\Bundle\\MakerBundle\\Command\\MakerCommand')] fn (): \Symfony\Bundle\MakerBundle\Command\MakerCommand => ($container->privates['maker.auto_command.make_security_custom'] ?? $container->load('getMaker_AutoCommand_MakeSecurityCustomService')));
    }
}
