<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_73Za615Service.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getMessageControllermarkReadService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_73Za615Service.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/get_ServiceLocator_73Za615Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllermarkReadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.73Za615.App\Controller\MessageController::markRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.73Za615.App\\Controller\\MessageController::markRead()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'em' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\MessageController::markRead()', $container);
    }
}
