<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_2S0AJ0MService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/get_ServiceLocator_2S0AJ0MService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_2S0AJ0MService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/get_ServiceLocator_2S0AJ0MService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2S0AJ0MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2S0AJ0M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2S0AJ0M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.2S0AJ0M.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.2S0AJ0M": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'category' => 'App\\Entity\\Category',
            'em' => '?',
        ]);
    }
}
