<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.value_resolver.argument_resolver.not_tagged_controller' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/NotTaggedControllerValueResolver.php';

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
        $a = ($container->privates['.service_locator.7R_WN15'] ?? $container->load('get_ServiceLocator_7RWN15Service'));
========
        $a = ($container->privates['.service_locator.TqJ.a_k'] ?? $container->load('get_ServiceLocator_TqJ_AKService'));
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
=======
        $a = ($container->privates['.service_locator.3pdjPNL'] ?? $container->load('get_ServiceLocator_3pdjPNLService'));
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php

        if (isset($container->privates['.debug.value_resolver.argument_resolver.not_tagged_controller'])) {
            return $container->privates['.debug.value_resolver.argument_resolver.not_tagged_controller'];
        }

        return $container->privates['.debug.value_resolver.argument_resolver.not_tagged_controller'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\NotTaggedControllerValueResolver($a), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
