<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_E51BVihService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/get_ServiceLocator_E51BVihService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_E51BVihService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/get_ServiceLocator_E51BVihService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E51BVihService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e51BVih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e51BVih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.e51BVih.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.e51BVih": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'em' => '?',
        ]);
    }
}
