<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getAvatarUploadTypeService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getAvatarUploadTypeService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getAvatarUploadTypeService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getAvatarUploadTypeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvatarUploadTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AvatarUploadType' shared autowired service.
     *
     * @return \App\Form\AvatarUploadType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AvatarUploadType.php';

        return $container->privates['App\\Form\\AvatarUploadType'] = new \App\Form\AvatarUploadType();
    }
}
