<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getArticleControllersearchService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getArticleControllersearchService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getArticleControllersearchService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getArticleControllersearchService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BCgH70e.App\Controller\ArticleController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCgH70e.App\\Controller\\ArticleController::search()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
        ]))->withContext('App\\Controller\\ArticleController::search()', $container);
    }
}
