<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getArticleControllershowOneService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getArticleControllershowOneService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getArticleControllershowOneService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getArticleControllershowOneService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllershowOneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hAbj0.E.App\Controller\ArticleController::showOne()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hAbj0.E.App\\Controller\\ArticleController::showOne()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.hAbj0.E.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.hAbj0.E": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
        ], [
            'article' => 'App\\Entity\\Article',
        ]))->withContext('App\\Controller\\ArticleController::showOne()', $container);
    }
}
