<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getArticle2Service.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getArticle2Service.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getArticle2Service.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getArticle2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticle2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.e51BVih.App\Entity\Article' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.e51BVih": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".');
    }
}
