<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getBaseControllerService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getBaseControllerService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getBaseControllerService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getBaseControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BaseController' shared autowired service.
     *
     * @return \App\Controller\BaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';

        $container->services['App\\Controller\\BaseController'] = $instance = new \App\Controller\BaseController();

        $instance->setContainer(($container->privates['.service_locator.xIvXWup'] ?? $container->load('get_ServiceLocator_XIvXWupService'))->withContext('App\\Controller\\BaseController', $container));

        return $instance;
    }
}
