<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getCategoryControllershowCategoryService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getCategoryControllershowCategoryService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getCategoryControllershowCategoryService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getCategoryControllershowCategoryService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllershowCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MTCWnA5.App\Controller\CategoryController::showCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MTCWnA5.App\\Controller\\CategoryController::showCategory()'] = ($container->privates['.service_locator.MTCWnA5'] ?? $container->load('get_ServiceLocator_MTCWnA5Service'))->withContext('App\\Controller\\CategoryController::showCategory()', $container);
    }
}
