<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getCategoryControllerupdateService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getCategoryControllerupdateService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getCategoryControllerupdateService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getCategoryControllerupdateService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2S0AJ0M.App\Controller\CategoryController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.2S0AJ0M'] ?? $container->load('get_ServiceLocator_2S0AJ0MService'));

        if (isset($container->privates['.service_locator.2S0AJ0M.App\\Controller\\CategoryController::update()'])) {
            return $container->privates['.service_locator.2S0AJ0M.App\\Controller\\CategoryController::update()'];
        }

        return $container->privates['.service_locator.2S0AJ0M.App\\Controller\\CategoryController::update()'] = $a->withContext('App\\Controller\\CategoryController::update()', $container);
    }
}
