<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getCommentTypeService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getCommentTypeService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getCommentTypeService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getCommentTypeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CommentType' shared autowired service.
     *
     * @return \App\Form\CommentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CommentType.php';

        return $container->privates['App\\Form\\CommentType'] = new \App\Form\CommentType();
    }
}
