<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getCategoryControllergetCategoriesService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getCategoryControllergetCategoriesService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getCategoryControllergetCategoriesService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getCategoryControllergetCategoriesService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllergetCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kdj54tv.App\Controller\CategoryController::getCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kdj54tv.App\\Controller\\CategoryController::getCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\CategoryRepository',
        ]))->withContext('App\\Controller\\CategoryController::getCategories()', $container);
    }
}
