<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getLexikJwtAuthentication_EnableEncryptionConfigCommandService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getLexikJwtAuthentication_EnableEncryptionConfigCommandService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getLexikJwtAuthentication_EnableEncryptionConfigCommandService.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getLexikJwtAuthentication_EnableEncryptionConfigCommandService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_EnableEncryptionConfigCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'lexik_jwt_authentication.enable_encryption_config_command' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Command\EnableEncryptionConfigCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Command/BuildDebugContainerTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Command/ContainerDebugCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Command/AbstractConfigCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Command/EnableEncryptionConfigCommand.php';

        $container->privates['lexik_jwt_authentication.enable_encryption_config_command'] = $instance = new \Lexik\Bundle\JWTAuthenticationBundle\Command\EnableEncryptionConfigCommand(NULL);

        $instance->setName('lexik:jwt:enable-encryption');
        $instance->setDescription('Enable Web-Token encryption support.');

        return $instance;
    }
}
