<?php

namespace ContainerTSb7RzG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllercheckUnreadMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JFzbWhz.App\Controller\MessageController::checkUnreadMessages()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JFzbWhz.App\\Controller\\MessageController::checkUnreadMessages()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'messageRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'security' => '?',
            'messageRepo' => 'App\\Repository\\MessageRepository',
        ]))->withContext('App\\Controller\\MessageController::checkUnreadMessages()', $container);
    }
}
