<?php

<<<<<<< HEAD:backend/var/cache/dev/ContainerXizlpCa/getUser3Service.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerO47bD08/getUser3Service.php
namespace ContainerO47bD08;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getUser3Service.php
=======
namespace ContainerTSb7RzG;
>>>>>>> 11fdd162a (Debut Notification):backend/var/cache/dev/ContainerTSb7RzG/getUser3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OHqHh3z.App\Entity\User' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OHqHh3z": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".');
    }
}
