<?php

namespace ContainerBDOmsVW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllermarkReadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.73Za615.App\Controller\MessageController::markRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.73Za615.App\\Controller\\MessageController::markRead()'] = ($container->privates['.service_locator.73Za615'] ?? $container->load('get_ServiceLocator_73Za615Service'))->withContext('App\\Controller\\MessageController::markRead()', $container);
    }
}
