<?php

namespace ContainerSNBavmf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_VsXeNPZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.vsXeNPZ' shared service.
     *
     * @return \App\Controller\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\VoteController::vote()": the $article argument is type-hinted with the non-existent class or interface: "App\\Controller\\Article". Did you forget to add a use statement?');
    }
}
