<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaXfp5L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaXfp5L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaXfp5L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaXfp5L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaXfp5L\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaXfp5L',
    'container.build_id' => 'b42371b4',
    'container.build_time' => 1749529769,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaXfp5L');
