controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
  path: /api/login
  methods: POST
  controller: lexik_jwt_authentication.controllers.authentication:login