<?php

namespace ContainerA5xbs4I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3CgzV3MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3CgzV3M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3CgzV3M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jwtManager' => ['privates', '.errored.vFElSzf', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::login()": the $jwtManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\JWTTokenManagerInterface". Did you forget to add a use statement?'],
        ], [
            'jwtManager' => '?',
        ]);
    }
}
