<?php

namespace ContainerXtFiXyE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MKaR5.9.App\Controller\CategoryController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MKaR5.9.App\\Controller\\CategoryController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\CategoryController::show()', $container);
    }
}
