<?php

namespace ContainerOjV1UrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ud_TUF1.App\Controller\ArticleController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ud_TUF1.App\\Controller\\ArticleController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.ud_TUF1.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.ud_TUF1": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'entityManager' => '?',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]))->withContext('App\\Controller\\ArticleController::update()', $container);
    }
}
