<?php

namespace ContainerOjV1UrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerNewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5LwPXeW.App\Controller\ArticleController::New()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5LwPXeW.App\\Controller\\ArticleController::New()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'catRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'entityManager' => '?',
            'catRepo' => 'App\\Repository\\CategoryRepository',
        ]))->withContext('App\\Controller\\ArticleController::New()', $container);
    }
}
