controllers_web:
    resource: '../src/Controller/Web/'
    type: attribute

controllers_api:
    resource: '../src/Controller/Api/'
    type: attribute
    prefix: /api

api_login_check:
    path: /api/login
    methods: POST