<?php

namespace ContainerSIui4P2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OHqHh3z.App\Controller\MessageController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OHqHh3z.App\\Controller\\MessageController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'receiver' => ['privates', '.errored..service_locator.OHqHh3z.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.OHqHh3z": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'messageRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'receiver' => 'App\\Entity\\User',
            'messageRepo' => 'App\\Repository\\MessageRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\MessageController::show()', $container);
    }
}
