<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerO47bD08/get_ServiceLocator_SShFNRVService.php
namespace ContainerO47bD08;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_TqJ_AKService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<<< HEAD:backend/var/cache/dev/ContainerO47bD08/get_ServiceLocator_SShFNRVService.php
class get_ServiceLocator_SShFNRVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sShFNRV' shared service.
========
class get_ServiceLocator_TqJ_AKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TqJ.a_k' shared service.
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_TqJ_AKService.php
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:backend/var/cache/dev/ContainerO47bD08/get_ServiceLocator_SShFNRVService.php
        return $container->privates['.service_locator.sShFNRV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
========
        return $container->privates['.service_locator.TqJ.a_k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/get_ServiceLocator_TqJ_AKService.php
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::New' => ['privates', '.service_locator.5LwPXeW.App\\Controller\\ArticleController::New()', 'getArticleControllerNewService', true],
            'App\\Controller\\ArticleController::update' => ['privates', '.service_locator.ud_TUF1.App\\Controller\\ArticleController::update()', 'getArticleControllerupdateService', true],
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.e51BVih.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.LXH8CDw.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController::showOne' => ['privates', '.service_locator.hAbj0.E.App\\Controller\\ArticleController::showOne()', 'getArticleControllershowOneService', true],
            'App\\Controller\\ArticleController::comment' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::comment()', 'getArticleControllercommentService', true],
            'App\\Controller\\ArticleController::search' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::search()', 'getArticleControllersearchService', true],
            'App\\Controller\\CategoryController::New' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategoryController::New()', 'getCategoryControllerNewService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController::showCategory' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::showCategory()', 'getCategoryControllershowCategoryService', true],
            'App\\Controller\\CategoryController::update' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::update()', 'getCategoryControllerupdateService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\CategoryController::getCategories' => ['privates', '.service_locator.kdj54tv.App\\Controller\\CategoryController::getCategories()', 'getCategoryControllergetCategoriesService', true],
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\MessageController::index()', 'getMessageControllerindexService', true],
            'App\\Controller\\MessageController::sendMessage' => ['privates', '.service_locator.7U6oXSr.App\\Controller\\MessageController::sendMessage()', 'getMessageControllersendMessageService', true],
            'App\\Controller\\MessageController::getMessages' => ['privates', '.service_locator.3Tauuah.App\\Controller\\MessageController::getMessages()', 'getMessageControllergetMessagesService', true],
            'App\\Controller\\MessageController::chatWithUser' => ['privates', '.service_locator.EpErdaJ.App\\Controller\\MessageController::chatWithUser()', 'getMessageControllerchatWithUserService', true],
            'App\\Controller\\MessageController::markRead' => ['privates', '.service_locator.73Za615.App\\Controller\\MessageController::markRead()', 'getMessageControllermarkReadService', true],
            'App\\Controller\\MessageController::show' => ['privates', '.service_locator.OHqHh3z.App\\Controller\\MessageController::show()', 'getMessageControllershowService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.O2RSURJ.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.FAUiyCT.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SearchController::search' => ['privates', '.service_locator.Lr3jbjP.App\\Controller\\SearchController::search()', 'getSearchControllersearchService', true],
            'App\\Controller\\SearchController::searchLive' => ['privates', '.service_locator.Lr3jbjP.App\\Controller\\SearchController::searchLive()', 'getSearchControllersearchLiveService', true],
            'App\\Controller\\VoteController::vote' => ['privates', '.service_locator.e51BVih.App\\Controller\\VoteController::vote()', 'getVoteControllervoteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:New' => ['privates', '.service_locator.5LwPXeW.App\\Controller\\ArticleController::New()', 'getArticleControllerNewService', true],
            'App\\Controller\\ArticleController:update' => ['privates', '.service_locator.ud_TUF1.App\\Controller\\ArticleController::update()', 'getArticleControllerupdateService', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.e51BVih.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.LXH8CDw.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController:showOne' => ['privates', '.service_locator.hAbj0.E.App\\Controller\\ArticleController::showOne()', 'getArticleControllershowOneService', true],
            'App\\Controller\\ArticleController:comment' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::comment()', 'getArticleControllercommentService', true],
            'App\\Controller\\ArticleController:search' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::search()', 'getArticleControllersearchService', true],
            'App\\Controller\\CategoryController:New' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategoryController::New()', 'getCategoryControllerNewService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController:showCategory' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::showCategory()', 'getCategoryControllershowCategoryService', true],
            'App\\Controller\\CategoryController:update' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::update()', 'getCategoryControllerupdateService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\CategoryController:getCategories' => ['privates', '.service_locator.kdj54tv.App\\Controller\\CategoryController::getCategories()', 'getCategoryControllergetCategoriesService', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\MessageController::index()', 'getMessageControllerindexService', true],
            'App\\Controller\\MessageController:sendMessage' => ['privates', '.service_locator.7U6oXSr.App\\Controller\\MessageController::sendMessage()', 'getMessageControllersendMessageService', true],
            'App\\Controller\\MessageController:getMessages' => ['privates', '.service_locator.3Tauuah.App\\Controller\\MessageController::getMessages()', 'getMessageControllergetMessagesService', true],
            'App\\Controller\\MessageController:chatWithUser' => ['privates', '.service_locator.EpErdaJ.App\\Controller\\MessageController::chatWithUser()', 'getMessageControllerchatWithUserService', true],
            'App\\Controller\\MessageController:markRead' => ['privates', '.service_locator.73Za615.App\\Controller\\MessageController::markRead()', 'getMessageControllermarkReadService', true],
            'App\\Controller\\MessageController:show' => ['privates', '.service_locator.OHqHh3z.App\\Controller\\MessageController::show()', 'getMessageControllershowService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.O2RSURJ.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.FAUiyCT.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SearchController:search' => ['privates', '.service_locator.Lr3jbjP.App\\Controller\\SearchController::search()', 'getSearchControllersearchService', true],
            'App\\Controller\\SearchController:searchLive' => ['privates', '.service_locator.Lr3jbjP.App\\Controller\\SearchController::searchLive()', 'getSearchControllersearchLiveService', true],
            'App\\Controller\\VoteController:vote' => ['privates', '.service_locator.e51BVih.App\\Controller\\VoteController::vote()', 'getVoteControllervoteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::New' => '?',
            'App\\Controller\\ArticleController::update' => '?',
            'App\\Controller\\ArticleController::delete' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ArticleController::showOne' => '?',
            'App\\Controller\\ArticleController::comment' => '?',
            'App\\Controller\\ArticleController::search' => '?',
            'App\\Controller\\CategoryController::New' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CategoryController::showCategory' => '?',
            'App\\Controller\\CategoryController::update' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::getCategories' => '?',
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\MessageController::sendMessage' => '?',
            'App\\Controller\\MessageController::getMessages' => '?',
            'App\\Controller\\MessageController::chatWithUser' => '?',
            'App\\Controller\\MessageController::markRead' => '?',
            'App\\Controller\\MessageController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SearchController::search' => '?',
            'App\\Controller\\SearchController::searchLive' => '?',
            'App\\Controller\\VoteController::vote' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:New' => '?',
            'App\\Controller\\ArticleController:update' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ArticleController:showOne' => '?',
            'App\\Controller\\ArticleController:comment' => '?',
            'App\\Controller\\ArticleController:search' => '?',
            'App\\Controller\\CategoryController:New' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CategoryController:showCategory' => '?',
            'App\\Controller\\CategoryController:update' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:getCategories' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\MessageController:sendMessage' => '?',
            'App\\Controller\\MessageController:getMessages' => '?',
            'App\\Controller\\MessageController:chatWithUser' => '?',
            'App\\Controller\\MessageController:markRead' => '?',
            'App\\Controller\\MessageController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SearchController:search' => '?',
            'App\\Controller\\SearchController:searchLive' => '?',
            'App\\Controller\\VoteController:vote' => '?',
        ]);
    }
}
