<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getArticleControllercommentService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getArticleControllercommentService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllercommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d6UE9.H.App\Controller\ArticleController::comment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::comment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.d6UE9.H.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.d6UE9.H": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ArticleController::comment()', $container);
    }
}
