<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getArticleControllershowService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getArticleControllershowService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BCgH70e.App\Controller\ArticleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCgH70e.App\\Controller\\ArticleController::show()'] = ($container->privates['.service_locator.BCgH70e'] ?? $container->load('get_ServiceLocator_BCgH70eService'))->withContext('App\\Controller\\ArticleController::show()', $container);
    }
}
