<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getArticleControllerdeleteService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getArticleControllerdeleteService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e51BVih.App\Controller\ArticleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.e51BVih'] ?? $container->load('get_ServiceLocator_E51BVihService'));

        if (isset($container->privates['.service_locator.e51BVih.App\\Controller\\ArticleController::delete()'])) {
            return $container->privates['.service_locator.e51BVih.App\\Controller\\ArticleController::delete()'];
        }

        return $container->privates['.service_locator.e51BVih.App\\Controller\\ArticleController::delete()'] = $a->withContext('App\\Controller\\ArticleController::delete()', $container);
    }
}
