<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getMessageControllerchatWithUserService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getMessageControllerchatWithUserService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllerchatWithUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EpErdaJ.App\Controller\MessageController::chatWithUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EpErdaJ.App\\Controller\\MessageController::chatWithUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'otherUser' => ['privates', '.errored..service_locator.EpErdaJ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.EpErdaJ": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'messageRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'otherUser' => 'App\\Entity\\User',
            'messageRepo' => 'App\\Repository\\MessageRepository',
            'em' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\MessageController::chatWithUser()', $container);
    }
}
