<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getResetPasswordControllerresetService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getResetPasswordControllerresetService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordControllerresetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FAUiyCT.App\Controller\ResetPasswordController::reset()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FAUiyCT.App\\Controller\\ResetPasswordController::reset()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\ResetPasswordController::reset()', $container);
    }
}
