<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getSearchControllerService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getSearchControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SearchController' shared autowired service.
     *
     * @return \App\Controller\SearchController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SearchController.php';

        $container->services['App\\Controller\\SearchController'] = $instance = new \App\Controller\SearchController();

        $instance->setContainer(($container->privates['.service_locator.xIvXWup'] ?? $container->load('get_ServiceLocator_XIvXWupService'))->withContext('App\\Controller\\SearchController', $container));

        return $instance;
    }
}
