<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getSearchControllersearchLiveService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getSearchControllersearchLiveService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllersearchLiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lr3jbjP.App\Controller\SearchController::searchLive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lr3jbjP.App\\Controller\\SearchController::searchLive()'] = ($container->privates['.service_locator.Lr3jbjP'] ?? $container->load('get_ServiceLocator_Lr3jbjPService'))->withContext('App\\Controller\\SearchController::searchLive()', $container);
    }
}
