<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerOjV1UrF/getVoteControllervoteService.php
namespace ContainerOjV1UrF;
========
namespace ContainerXizlpCa;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerXizlpCa/getVoteControllervoteService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoteControllervoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e51BVih.App\Controller\VoteController::vote()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e51BVih.App\\Controller\\VoteController::vote()'] = ($container->privates['.service_locator.e51BVih'] ?? $container->load('get_ServiceLocator_E51BVihService'))->withContext('App\\Controller\\VoteController::vote()', $container);
    }
}
