<?php

namespace ContainerVlVdiZ7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G_HJBSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G._HJBS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G._HJBS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored.vsXeNPZ', NULL, 'Cannot determine controller argument for "App\\Controller\\VoteController::vote()": the $article argument is type-hinted with the non-existent class or interface: "App\\Controller\\Article". Did you forget to add a use statement?'],
            'em' => ['privates', '.errored.m0qfmMr', NULL, 'Cannot determine controller argument for "App\\Controller\\VoteController::vote()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'article' => '?',
            'em' => '?',
        ]);
    }
}
