<?php

namespace ContainerVlVdiZ7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BCgH70e.App\Controller\ArticleController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCgH70e.App\\Controller\\ArticleController::search()'] = ($container->privates['.service_locator.BCgH70e'] ?? $container->load('get_ServiceLocator_BCgH70eService'))->withContext('App\\Controller\\ArticleController::search()', $container);
    }
}
