<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEAT7fqz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEAT7fqz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEAT7fqz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEAT7fqz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEAT7fqz\App_KernelDevDebugContainer([
    'container.build_hash' => 'EAT7fqz',
    'container.build_id' => '02305233',
    'container.build_time' => 1749162039,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEAT7fqz');
