<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYb8WDxP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYb8WDxP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYb8WDxP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYb8WDxP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYb8WDxP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yb8WDxP',
    'container.build_id' => '4b625017',
    'container.build_time' => 1749380494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYb8WDxP');
