<?php

namespace ContainerYb8WDxP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserProfileController' shared autowired service.
     *
     * @return \App\Controller\UserProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserProfileController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->services['App\\Controller\\UserProfileController'] = $instance = new \App\Controller\UserProfileController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')), (\dirname(__DIR__, 4).'/public/uploads/avatars'));

        $instance->setContainer(($container->privates['.service_locator.rvwW9pW'] ?? $container->load('get_ServiceLocator_RvwW9pWService'))->withContext('App\\Controller\\UserProfileController', $container));

        return $instance;
    }
}
