<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerO47bD08/getArticle4Service.php
namespace ContainerO47bD08;
========
namespace ContainerSamTBcx;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerSamTBcx/getArticle4Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticle4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ud_TUF1.App\Entity\Article' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ud_TUF1": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".');
    }
}
