<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerO47bD08/getTurbo_Mercure_Default_BroadcasterService.php
namespace ContainerO47bD08;
========
namespace ContainerSamTBcx;
>>>>>>>> 7c704d2aa (Final Pagination react cote Backend):backend/var/cache/dev/ContainerSamTBcx/getTurbo_Mercure_Default_BroadcasterService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTurbo_Mercure_Default_BroadcasterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'turbo.mercure.default.broadcaster' shared service.
     *
     * @return \Symfony\UX\Turbo\Bridge\Mercure\Broadcaster
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-turbo/src/Broadcaster/BroadcasterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-turbo/src/Bridge/Mercure/Broadcaster.php';

        return $container->privates['turbo.mercure.default.broadcaster'] = new \Symfony\UX\Turbo\Bridge\Mercure\Broadcaster('default', ($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)));
    }
}
