<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8HekixZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8HekixZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8HekixZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8HekixZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8HekixZ\App_KernelDevDebugContainer([
    'container.build_hash' => '8HekixZ',
    'container.build_id' => '2f3a297b',
    'container.build_time' => 1748155360,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8HekixZ');
