<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI9bMVj1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI9bMVj1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI9bMVj1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI9bMVj1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI9bMVj1\App_KernelDevDebugContainer([
    'container.build_hash' => 'I9bMVj1',
    'container.build_id' => 'e3cd2be6',
    'container.build_time' => 1748540639,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI9bMVj1');
