<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQR1JAVc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQR1JAVc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQR1JAVc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQR1JAVc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQR1JAVc\App_KernelDevDebugContainer([
    'container.build_hash' => 'QR1JAVc',
    'container.build_id' => 'a5467421',
    'container.build_time' => 1747889055,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQR1JAVc');
