<?php

namespace ContainerTtHPJin;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lr3jbjP.App\Controller\SearchController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lr3jbjP.App\\Controller\\SearchController::search()'] = ($container->privates['.service_locator.Lr3jbjP'] ?? $container->load('get_ServiceLocator_Lr3jbjPService'))->withContext('App\\Controller\\SearchController::search()', $container);
    }
}
